services:
  data-ingest-service:
    image: 'ghcr.io/hamalais-osakunta/saunatonttu/data-ingest-service:latest'
    depends_on:
      - timescaledb
    networks:
      - monitoring
    restart: always
    environment:
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - 'DB_NAME=${DB_NAME}'
      - 'DB_USER=${DB_USER}'
      - 'DB_PASSWORD=${DB_PASSWORD}'

  timescaledb:
    image: 'timescale/timescaledb:latest-pg14'
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - 'timescaledb_data:/var/lib/postgresql/data'
    networks:
      - monitoring
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      - 'GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}'
    volumes:
      - 'grafana_data:/var/lib/grafana'
    depends_on:
      - timescaledb
    networks:
      - monitoring
    restart: always
networks:
  monitoring:
volumes:
  timescaledb_data: null
  grafana_data: null
